package com.insurance.capability1process;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TimeProvider implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TimeProvider() {
    }




}